### ISSUE TITLE
cargo-binutils 版本过低

### ISSUE THREAD

**Issue by BillXWB** [LearningOS/rCore-Tutorial-Code-2022S#2]
os/Makefile 中依赖的 cargo-binutils 版本与较新的 LLVM 不兼容，会导致错误：
```shell
llvm-objdump: error: unknown argument '-c'
```
cargo-binutils 在 https://github.com/rust-embedded/cargo-binutils/pull/92 中已经进行了修复。

**Comment by Gallium70** [comment]
这个问题我没有成功复现，可否提供一下你使用的相关工具的版本？这个-C是来自 [config](https://github.com/LearningOS/rCore-Tutorial-Code-2022S/blob/ch3/os/.cargo/config) 文件吗

**Comment by BillXWB** [comment]
我的环境是 LLVM 13.0.1. 我看了一下 https://github.com/rust-embedded/cargo-binutils/pull/92 的提交，是因为 LLVM 11 及之后把 llvm-objdump 的 `-arch-name` 改成 `--arch-name` 了，老版本的 cargo-objdump 调用的时候就会出这个错误。应该是不影响实验使用的部分，但是我自己用 cargo-objdump 的时候就会出问题。

**Comment by Gallium70** [comment]
已将cargo-binutils版本更新到~0.3
